#!/usr/bin/env bash
#Configuring web-01 to have HTTP response header

#updating the packages
sudo apt-get update

#install nginx
sudo apt-get install -y nginx

#creating an index.html page
echo "Hello World!" | sudo tee /var/www/html/index.html

#perform redirection
new_string="server_name _;\n\trewrite ^\/redirect_me https:\/\/github.com\/Jyde24 permanent;"
sudo sed -i "s/server_name _;/$new_string/" /etc/nginx/sites-enabled/default

#Creating a custom error page
echo "Ceci n'est pas une page" | sudo tee /var/www/html/404.html

#Custome HTTP response header
sudo sed -i "server_name _;/a add_header X-Served-By $HOSTNAME;" /etc/nginx/sites-enabled/default

#Test for syntax error
sudo nginx -t

#restart nginx
sudo service nginx restart

#Author Chukwunonso Jide
